export const theme = {
  green: '#00B14F',
  greenDark: '#009245',
  bg: '#FFFFFF',
  surface: '#F7F7F7',
  text: '#1C1C1C',
  textMuted: '#707070',
  danger: '#E5484D',
  gold: '#D4A017',
  radius: 12,
  pad: 16,
  /** Max app width on web — keeps desktop browsers in a phone-sized frame. */
  mobileWebWidth: 430,
  /** Doodle font family — loaded in app/_layout via @expo-google-fonts/mali. */
  font: 'Mali_600SemiBold',
  fontBold: 'Mali_700Bold',
  /**
   * Doodle ("เบรค, อีเวน") design language — hand-drawn sketchbook look.
   * Ported from prototypes/doodle.html. Used by the Home slice; legacy keys
   * above remain for screens not yet migrated.
   */
  doodle: {
    paper: '#FBF8F0',
    paper2: '#F4EFE2',
    card: '#FFFEFA',
    grid: '#E4DCC8',
    ink: '#3A3530',
    inkSoft: '#7C746A',
    pencil: '#5A5450',
    coral: '#F2664B',
    blue: '#4D8FC0',
    yellow: '#F4C24A',
    mint: '#6FBE9B',
    grape: '#9B6FC0',
    coralWash: '#FCE0DA',
    blueWash: '#DCEAF4',
    mintWash: '#DCEFE6',
    yellowWash: '#FBEFC9',
  },
  dating: {
    rose: '#FECDD3',
    rosePressed: '#FDA4AF',
    nope: '#FEE2E2',
    nopePressed: '#FCA5A5',
    rareBg: '#FEF3C7',
    rareText: '#92400E',
    beatBg: '#FFF7ED',
    userBubble: '#DCFCE7',
    online: '#22C55E',
    shadow: 'rgba(0, 0, 0, 0.08)',
  },
  tinder: {
    pink: '#FD297B',
    pinkLight: '#FECDD3',
    nope: '#FF4458',
    nopeBg: '#FEE2E2',
    like: '#21D07C',
    likeBg: '#DCFCE7',
    superLike: '#1DA1F2',
    superLikeBg: '#DBEAFE',
    boost: '#A855F7',
    rewind: '#FBBF24',
    cardShadow: 'rgba(0, 0, 0, 0.15)',
  },
} as const;
